{{- if or .Values.secrets.redisPassword .Values.secrets.jwtSecret .Values.secrets.encryptionKey .Values.secrets.indodaxWsToken }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "api.fullname" . }}-secrets
  namespace: {{ .Values.namespace | default .Release.Namespace }}
  labels:
    {{- include "api.labels" . | nindent 4 }}
type: Opaque
data:
  {{- if .Values.secrets.redisPassword }}
  redis-password: {{ .Values.secrets.redisPassword | b64enc }}
  {{- end }}
  {{- if .Values.secrets.jwtSecret }}
  jwt-secret: {{ .Values.secrets.jwtSecret | b64enc }}
  {{- end }}
  {{- if .Values.secrets.encryptionKey }}
  encryption-key: {{ .Values.secrets.encryptionKey | b64enc }}
  {{- end }}
  {{- if .Values.secrets.indodaxWsToken }}
  indodax-ws-token: {{ .Values.secrets.indodaxWsToken | b64enc }}
  {{- end }}
{{- end }}

